// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	wallet.proto

It has these top-level messages:
	BalanceRequest
	BalanceResponse
	Account
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BalanceRequest struct {
	Addresses        []string `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BalanceRequest) Reset()                    { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()               {}
func (*BalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BalanceRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type BalanceResponse struct {
	Accounts         []*Account `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *BalanceResponse) Reset()                    { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string            { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()               {}
func (*BalanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BalanceResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Account struct {
	Address          *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Total            *uint64 `protobuf:"varint,2,req,name=total" json:"total,omitempty"`
	Spendable        *uint64 `protobuf:"varint,3,req,name=spendable" json:"spendable,omitempty"`
	Reward           *uint64 `protobuf:"varint,4,req,name=reward" json:"reward,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Account) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *Account) GetTotal() uint64 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *Account) GetSpendable() uint64 {
	if m != nil && m.Spendable != nil {
		return *m.Spendable
	}
	return 0
}

func (m *Account) GetReward() uint64 {
	if m != nil && m.Reward != nil {
		return *m.Reward
	}
	return 0
}

func init() {
	proto.RegisterType((*BalanceRequest)(nil), "rpc.BalanceRequest")
	proto.RegisterType((*BalanceResponse)(nil), "rpc.BalanceResponse")
	proto.RegisterType((*Account)(nil), "rpc.Account")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WalletService service

type WalletServiceClient interface {
	Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
}

type walletServiceClient struct {
	cc *grpc.ClientConn
}

func NewWalletServiceClient(cc *grpc.ClientConn) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := grpc.Invoke(ctx, "/rpc.WalletService/Balance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WalletService service

type WalletServiceServer interface {
	Balance(context.Context, *BalanceRequest) (*BalanceResponse, error)
}

func RegisterWalletServiceServer(s *grpc.Server, srv WalletServiceServer) {
	s.RegisterService(&_WalletService_serviceDesc, srv)
}

func _WalletService_Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.WalletService/Balance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Balance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Balance",
			Handler:    _WalletService_Balance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xe9, 0x6e, 0xeb, 0xba, 0x63, 0x55, 0x18, 0x8b, 0x04, 0xf1, 0xb0, 0xec, 0x69, 0x4f,
	0x7b, 0x28, 0xde, 0x3c, 0x59, 0xf0, 0x0f, 0xc4, 0x83, 0xe0, 0x6d, 0xcc, 0xce, 0x41, 0x08, 0x49,
	0x4c, 0x52, 0xfb, 0xf7, 0xa5, 0x49, 0xda, 0xb2, 0xc7, 0xf7, 0xbd, 0xc7, 0xf0, 0xde, 0xc0, 0xfa,
	0x40, 0x5a, 0x73, 0x1c, 0x9d, 0xb7, 0xd1, 0x62, 0xed, 0x9d, 0xea, 0x47, 0xb8, 0xdb, 0x91, 0x26,
	0xa3, 0x58, 0xf2, 0xef, 0x9e, 0x43, 0xc4, 0x67, 0x68, 0x69, 0x9a, 0x3c, 0x87, 0xc0, 0x41, 0x2c,
	0xba, 0x7a, 0x68, 0xe5, 0x05, 0xf4, 0xaf, 0x70, 0x7f, 0xce, 0x07, 0x67, 0x4d, 0x60, 0x1c, 0xe0,
	0x9a, 0x94, 0xb2, 0x7b, 0x13, 0x73, 0xfe, 0x66, 0xbb, 0x1e, 0xbd, 0x53, 0xe3, 0x5b, 0x86, 0xf2,
	0xec, 0xf6, 0x16, 0x9a, 0x02, 0x51, 0x40, 0x53, 0x8e, 0x8a, 0x45, 0x57, 0x0d, 0xad, 0x3c, 0x49,
	0xdc, 0xc0, 0x2a, 0xda, 0x48, 0x5a, 0x54, 0x5d, 0x35, 0x2c, 0x65, 0x16, 0xc7, 0x56, 0xc1, 0xb1,
	0x99, 0xe8, 0x5b, 0xb3, 0xa8, 0x93, 0x73, 0x01, 0xf8, 0x08, 0x57, 0x9e, 0x0f, 0xe4, 0x27, 0xb1,
	0x4c, 0x56, 0x51, 0xdb, 0x77, 0xb8, 0xfd, 0x4c, 0x93, 0x3f, 0xd8, 0xff, 0xfd, 0x28, 0xc6, 0x17,
	0x68, 0x4a, 0x7d, 0x7c, 0x48, 0x25, 0xe7, 0xe3, 0x9f, 0x36, 0x73, 0x98, 0x17, 0xee, 0x56, 0x5f,
	0xc7, 0x5f, 0xfd, 0x07, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xed, 0x7a, 0x84, 0x3f, 0x01, 0x00, 0x00,
}
