// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	wallet.proto

It has these top-level messages:
	AccountRequest
	AccountResponse
	Account
	Transaction
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountRequest struct {
	Addresses        []string `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AccountRequest) Reset()                    { *m = AccountRequest{} }
func (m *AccountRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()               {}
func (*AccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type AccountResponse struct {
	Accounts         []*Account `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *AccountResponse) Reset()                    { *m = AccountResponse{} }
func (m *AccountResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()               {}
func (*AccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Account struct {
	Address          *string        `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Spendable        *uint64        `protobuf:"varint,3,req,name=spendable" json:"spendable,omitempty"`
	Transactions     []*Transaction `protobuf:"bytes,5,rep,name=transactions" json:"transactions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Account) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *Account) GetSpendable() uint64 {
	if m != nil && m.Spendable != nil {
		return *m.Spendable
	}
	return 0
}

func (m *Account) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Transaction struct {
	Amount           *uint64 `protobuf:"varint,1,req,name=amount" json:"amount,omitempty"`
	Spender          *string `protobuf:"bytes,2,req,name=spender" json:"spender,omitempty"`
	Receiver         *string `protobuf:"bytes,3,req,name=receiver" json:"receiver,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Transaction) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *Transaction) GetSpender() string {
	if m != nil && m.Spender != nil {
		return *m.Spender
	}
	return ""
}

func (m *Transaction) GetReceiver() string {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountRequest)(nil), "rpc.AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "rpc.AccountResponse")
	proto.RegisterType((*Account)(nil), "rpc.Account")
	proto.RegisterType((*Transaction)(nil), "rpc.Transaction")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WalletService service

type WalletServiceClient interface {
	Account(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
}

type walletServiceClient struct {
	cc *grpc.ClientConn
}

func NewWalletServiceClient(cc *grpc.ClientConn) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) Account(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := grpc.Invoke(ctx, "/rpc.WalletService/Account", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WalletService service

type WalletServiceServer interface {
	Account(context.Context, *AccountRequest) (*AccountResponse, error)
}

func RegisterWalletServiceServer(s *grpc.Server, srv WalletServiceServer) {
	s.RegisterService(&_WalletService_serviceDesc, srv)
}

func _WalletService_Account_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Account(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.WalletService/Account",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Account(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Account",
			Handler:    _WalletService_Account_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0x93, 0x96, 0x36, 0xd7, 0xf0, 0x21, 0x83, 0x90, 0x55, 0x31, 0x44, 0x99, 0x32, 0x65,
	0xa8, 0xd8, 0x98, 0x40, 0xe2, 0x0f, 0x18, 0x24, 0x24, 0x98, 0x8c, 0x73, 0x43, 0xa4, 0x10, 0x1b,
	0x9f, 0xdb, 0xfe, 0x7d, 0x64, 0x3b, 0x4d, 0xc8, 0xf8, 0x3e, 0xe4, 0xf7, 0xfc, 0x0e, 0xf2, 0x93,
	0xec, 0x3a, 0x74, 0xb5, 0xb1, 0xda, 0x69, 0x96, 0x5a, 0xa3, 0xca, 0x1a, 0xae, 0x9e, 0x95, 0xd2,
	0x87, 0xde, 0x09, 0xfc, 0x3d, 0x20, 0x39, 0xf6, 0x00, 0x99, 0x6c, 0x1a, 0x8b, 0x44, 0x48, 0x7c,
	0x51, 0xa4, 0x55, 0x26, 0x26, 0xa2, 0x7c, 0x82, 0xeb, 0xd1, 0x4f, 0x46, 0xf7, 0x84, 0xac, 0x82,
	0x8d, 0x8c, 0x54, 0xf4, 0x6f, 0xf7, 0x79, 0x6d, 0x8d, 0xaa, 0xcf, 0xbe, 0x51, 0x2d, 0x4f, 0xb0,
	0x1e, 0x48, 0xc6, 0x61, 0x3d, 0x3c, 0xca, 0x17, 0x45, 0x52, 0x65, 0xe2, 0x0c, 0x7d, 0x3e, 0x19,
	0xec, 0x1b, 0xf9, 0xdd, 0x21, 0x4f, 0x8b, 0xa4, 0x5a, 0x8a, 0x89, 0x60, 0x8f, 0x90, 0x3b, 0x2b,
	0x7b, 0x92, 0xca, 0xb5, 0xba, 0x27, 0xbe, 0x0a, 0x81, 0x37, 0x21, 0xf0, 0x7d, 0x12, 0xc4, 0xcc,
	0x55, 0x7e, 0xc1, 0xf6, 0x9f, 0xc8, 0xee, 0xe1, 0x42, 0xfe, 0xf8, 0x1a, 0x21, 0x7b, 0x29, 0x06,
	0xe4, 0x4b, 0x85, 0x24, 0xb4, 0x3c, 0x89, 0xa5, 0x06, 0xc8, 0x76, 0xb0, 0xb1, 0xa8, 0xb0, 0x3d,
	0xa2, 0x0d, 0x9d, 0x32, 0x31, 0xe2, 0xfd, 0x2b, 0x5c, 0x7e, 0x84, 0x5d, 0xdf, 0xd0, 0x1e, 0x5b,
	0xe5, 0x3b, 0x8e, 0xdf, 0xbc, 0x9d, 0x2d, 0x11, 0x17, 0xde, 0xdd, 0xcd, 0xc9, 0x38, 0xe3, 0xcb,
	0xea, 0xd3, 0x1f, 0xe4, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xab, 0x40, 0x18, 0x9f, 0xa4, 0x01, 0x00,
	0x00,
}
