// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/sync.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import entities "github.com/tclchiam/oxidize-go/encoding"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetBestHeaderRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetBestHeaderRequest) Reset()                    { *m = GetBestHeaderRequest{} }
func (m *GetBestHeaderRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBestHeaderRequest) ProtoMessage()               {}
func (*GetBestHeaderRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type GetBestHeaderResponse struct {
	Header           *entities.BlockHeader `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *GetBestHeaderResponse) Reset()                    { *m = GetBestHeaderResponse{} }
func (m *GetBestHeaderResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBestHeaderResponse) ProtoMessage()               {}
func (*GetBestHeaderResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetBestHeaderResponse) GetHeader() *entities.BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetHeadersRequest struct {
	LatestHash       []byte  `protobuf:"bytes,1,req,name=latestHash" json:"latestHash,omitempty"`
	LatestIndex      *uint64 `protobuf:"varint,2,req,name=latestIndex" json:"latestIndex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetHeadersRequest) Reset()                    { *m = GetHeadersRequest{} }
func (m *GetHeadersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetHeadersRequest) ProtoMessage()               {}
func (*GetHeadersRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetHeadersRequest) GetLatestHash() []byte {
	if m != nil {
		return m.LatestHash
	}
	return nil
}

func (m *GetHeadersRequest) GetLatestIndex() uint64 {
	if m != nil && m.LatestIndex != nil {
		return *m.LatestIndex
	}
	return 0
}

type GetHeadersResponse struct {
	HeaderCount      *uint32                 `protobuf:"varint,1,req,name=headerCount" json:"headerCount,omitempty"`
	Headers          []*entities.BlockHeader `protobuf:"bytes,2,rep,name=headers" json:"headers,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GetHeadersResponse) Reset()                    { *m = GetHeadersResponse{} }
func (m *GetHeadersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetHeadersResponse) ProtoMessage()               {}
func (*GetHeadersResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GetHeadersResponse) GetHeaderCount() uint32 {
	if m != nil && m.HeaderCount != nil {
		return *m.HeaderCount
	}
	return 0
}

func (m *GetHeadersResponse) GetHeaders() []*entities.BlockHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

type GetBlockRequest struct {
	Hash             []byte  `protobuf:"bytes,1,req,name=hash" json:"hash,omitempty"`
	Index            *uint64 `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetBlockRequest) Reset()                    { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()               {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *GetBlockRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *GetBlockRequest) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type GetBlockResponse struct {
	Block            *entities.Block `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GetBlockResponse) Reset()                    { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()               {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *GetBlockResponse) GetBlock() *entities.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterType((*GetBestHeaderRequest)(nil), "rpc.GetBestHeaderRequest")
	proto.RegisterType((*GetBestHeaderResponse)(nil), "rpc.GetBestHeaderResponse")
	proto.RegisterType((*GetHeadersRequest)(nil), "rpc.GetHeadersRequest")
	proto.RegisterType((*GetHeadersResponse)(nil), "rpc.GetHeadersResponse")
	proto.RegisterType((*GetBlockRequest)(nil), "rpc.GetBlockRequest")
	proto.RegisterType((*GetBlockResponse)(nil), "rpc.GetBlockResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SyncService service

type SyncServiceClient interface {
	GetBestHeader(ctx context.Context, in *GetBestHeaderRequest, opts ...grpc.CallOption) (*GetBestHeaderResponse, error)
	GetHeaders(ctx context.Context, in *GetHeadersRequest, opts ...grpc.CallOption) (*GetHeadersResponse, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
}

type syncServiceClient struct {
	cc *grpc.ClientConn
}

func NewSyncServiceClient(cc *grpc.ClientConn) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) GetBestHeader(ctx context.Context, in *GetBestHeaderRequest, opts ...grpc.CallOption) (*GetBestHeaderResponse, error) {
	out := new(GetBestHeaderResponse)
	err := grpc.Invoke(ctx, "/rpc.SyncService/GetBestHeader", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetHeaders(ctx context.Context, in *GetHeadersRequest, opts ...grpc.CallOption) (*GetHeadersResponse, error) {
	out := new(GetHeadersResponse)
	err := grpc.Invoke(ctx, "/rpc.SyncService/GetHeaders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := grpc.Invoke(ctx, "/rpc.SyncService/GetBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SyncService service

type SyncServiceServer interface {
	GetBestHeader(context.Context, *GetBestHeaderRequest) (*GetBestHeaderResponse, error)
	GetHeaders(context.Context, *GetHeadersRequest) (*GetHeadersResponse, error)
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
}

func RegisterSyncServiceServer(s *grpc.Server, srv SyncServiceServer) {
	s.RegisterService(&_SyncService_serviceDesc, srv)
}

func _SyncService_GetBestHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBestHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetBestHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SyncService/GetBestHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetBestHeader(ctx, req.(*GetBestHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeadersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SyncService/GetHeaders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetHeaders(ctx, req.(*GetHeadersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SyncService/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SyncService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBestHeader",
			Handler:    _SyncService_GetBestHeader_Handler,
		},
		{
			MethodName: "GetHeaders",
			Handler:    _SyncService_GetHeaders_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _SyncService_GetBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/sync.proto",
}

func init() { proto.RegisterFile("rpc/sync.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0x43, 0x81, 0xf7, 0x35, 0x53, 0x11, 0x9d, 0xf0, 0xcf, 0x1e, 0x4c, 0xd3, 0xc4, 0x84,
	0x8b, 0x25, 0xe1, 0x62, 0x8c, 0xf1, 0x82, 0x09, 0xe8, 0xb5, 0xc4, 0x8b, 0x37, 0x5c, 0x26, 0xd0,
	0x48, 0x76, 0xeb, 0xee, 0x62, 0xe4, 0x43, 0xfa, 0x9d, 0x4c, 0xbb, 0x5b, 0x58, 0x10, 0x6f, 0x9d,
	0xdf, 0xcc, 0x3c, 0xf3, 0x74, 0x66, 0xe1, 0x4c, 0x66, 0x6c, 0xa0, 0x36, 0x9c, 0xc5, 0x99, 0x14,
	0x5a, 0x60, 0x55, 0x66, 0x2c, 0xe8, 0x12, 0x67, 0x62, 0x9e, 0xf2, 0xc5, 0x80, 0xb8, 0x4e, 0x75,
	0x4a, 0xca, 0x64, 0xa3, 0x0e, 0xb4, 0x26, 0xa4, 0x47, 0xa4, 0xf4, 0x13, 0xcd, 0xe6, 0x24, 0x13,
	0xfa, 0x58, 0x93, 0xd2, 0xd1, 0x18, 0xda, 0x07, 0x5c, 0x65, 0x82, 0x2b, 0xc2, 0x1b, 0xf8, 0xb7,
	0x2c, 0x48, 0xaf, 0x12, 0x7a, 0x7d, 0x7f, 0xd8, 0x8e, 0xb7, 0x8a, 0xa3, 0x95, 0x60, 0xef, 0xb6,
	0xdc, 0x16, 0x45, 0x2f, 0x70, 0x31, 0x21, 0xab, 0xa1, 0xac, 0x38, 0x5e, 0x01, 0xac, 0x66, 0x3a,
	0xd7, 0x9e, 0xa9, 0x65, 0xa1, 0x73, 0x9a, 0x38, 0x04, 0x43, 0xf0, 0x4d, 0xf4, 0xcc, 0xe7, 0xf4,
	0xd5, 0xf3, 0x42, 0xaf, 0x5f, 0x4b, 0x5c, 0x14, 0x2d, 0x00, 0x5d, 0x59, 0xeb, 0x2d, 0x04, 0xdf,
	0x8c, 0x7d, 0x14, 0x6b, 0xae, 0x0b, 0xe1, 0x46, 0xe2, 0x22, 0x1c, 0xc0, 0x7f, 0x13, 0xaa, 0x9e,
	0x17, 0x56, 0xff, 0xb6, 0x5f, 0x56, 0x45, 0xf7, 0xd0, 0xcc, 0xf7, 0x90, 0xa7, 0x4a, 0xf7, 0x08,
	0xb5, 0xe5, 0xce, 0x77, 0xf1, 0x8d, 0x2d, 0xa8, 0xa7, 0x8e, 0x57, 0x13, 0x44, 0x77, 0x70, 0xbe,
	0x6b, 0xb6, 0x1e, 0xaf, 0xa1, 0xfe, 0x96, 0x03, 0xbb, 0xbe, 0xe6, 0xc1, 0xfc, 0xc4, 0x64, 0x87,
	0xdf, 0x15, 0xf0, 0xa7, 0x1b, 0xce, 0xa6, 0x24, 0x3f, 0x53, 0x46, 0x38, 0x86, 0xc6, 0xde, 0x3d,
	0xf0, 0x32, 0x96, 0x19, 0x8b, 0x8f, 0xdd, 0x2e, 0x08, 0x8e, 0xa5, 0xec, 0xf8, 0x07, 0x80, 0xdd,
	0xe2, 0xb0, 0x53, 0x56, 0xee, 0x1f, 0x28, 0xe8, 0xfe, 0xe2, 0xb6, 0xfd, 0x16, 0x4e, 0xca, 0x3f,
	0xc2, 0xd6, 0x76, 0x8c, 0xb3, 0x9d, 0xa0, 0x7d, 0x40, 0x4d, 0xe3, 0xa8, 0xfe, 0x9a, 0xbf, 0xc3,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0x31, 0xeb, 0x6d, 0x9d, 0x02, 0x00, 0x00,
}
