// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package encoding is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Block
	BlockHeader
	Transaction
	Output
	OutputReference
	SignedInput
	UnsignedInput
*/
package encoding

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Header           *BlockHeader   `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	Transactions     []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockHeader struct {
	Index            *uint64 `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	PreviousHash     []byte  `protobuf:"bytes,2,req,name=previousHash" json:"previousHash,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	TransactionsHash []byte  `protobuf:"bytes,4,req,name=transactionsHash" json:"transactionsHash,omitempty"`
	Nonce            *uint64 `protobuf:"varint,5,req,name=nonce" json:"nonce,omitempty"`
	Hash             []byte  `protobuf:"bytes,6,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockHeader) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *BlockHeader) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *BlockHeader) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetTransactionsHash() []byte {
	if m != nil {
		return m.TransactionsHash
	}
	return nil
}

func (m *BlockHeader) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Transaction struct {
	Id               []byte         `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Inputs           []*SignedInput `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty"`
	Outputs          []*Output      `protobuf:"bytes,3,rep,name=outputs" json:"outputs,omitempty"`
	Secret           []byte         `protobuf:"bytes,4,req,name=secret" json:"secret,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Transaction) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Transaction) GetInputs() []*SignedInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Transaction) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Transaction) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

type Output struct {
	Index            *uint32 `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	Value            *uint32 `protobuf:"varint,2,req,name=value" json:"value,omitempty"`
	PublicKeyHash    []byte  `protobuf:"bytes,3,req,name=publicKeyHash" json:"publicKeyHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Output) Reset()                    { *m = Output{} }
func (m *Output) String() string            { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()               {}
func (*Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Output) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *Output) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *Output) GetPublicKeyHash() []byte {
	if m != nil {
		return m.PublicKeyHash
	}
	return nil
}

type OutputReference struct {
	Id               []byte  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Output           *Output `protobuf:"bytes,2,req,name=output" json:"output,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OutputReference) Reset()                    { *m = OutputReference{} }
func (m *OutputReference) String() string            { return proto.CompactTextString(m) }
func (*OutputReference) ProtoMessage()               {}
func (*OutputReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OutputReference) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *OutputReference) GetOutput() *Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type SignedInput struct {
	Reference        *OutputReference `protobuf:"bytes,1,req,name=reference" json:"reference,omitempty"`
	PublicKey        []byte           `protobuf:"bytes,2,req,name=publicKey" json:"publicKey,omitempty"`
	Signature        []byte           `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SignedInput) Reset()                    { *m = SignedInput{} }
func (m *SignedInput) String() string            { return proto.CompactTextString(m) }
func (*SignedInput) ProtoMessage()               {}
func (*SignedInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SignedInput) GetReference() *OutputReference {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *SignedInput) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *SignedInput) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type UnsignedInput struct {
	Reference        *OutputReference `protobuf:"bytes,1,req,name=reference" json:"reference,omitempty"`
	PublicKey        []byte           `protobuf:"bytes,2,req,name=publicKey" json:"publicKey,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *UnsignedInput) Reset()                    { *m = UnsignedInput{} }
func (m *UnsignedInput) String() string            { return proto.CompactTextString(m) }
func (*UnsignedInput) ProtoMessage()               {}
func (*UnsignedInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UnsignedInput) GetReference() *OutputReference {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *UnsignedInput) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "encoding.Block")
	proto.RegisterType((*BlockHeader)(nil), "encoding.BlockHeader")
	proto.RegisterType((*Transaction)(nil), "encoding.Transaction")
	proto.RegisterType((*Output)(nil), "encoding.Output")
	proto.RegisterType((*OutputReference)(nil), "encoding.OutputReference")
	proto.RegisterType((*SignedInput)(nil), "encoding.SignedInput")
	proto.RegisterType((*UnsignedInput)(nil), "encoding.UnsignedInput")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xb1, 0x8e, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0x3b, 0x36, 0xdc, 0xd8, 0x86, 0xd3, 0xea, 0x40, 0x46, 0xa2, 0x88, 0x56, 0x14,
	0xd1, 0x49, 0xa4, 0xa0, 0x41, 0xb4, 0x54, 0x87, 0xae, 0x40, 0x5a, 0xa0, 0xa1, 0x33, 0xf6, 0x24,
	0x59, 0x91, 0xec, 0x9a, 0xdd, 0x75, 0x44, 0x5a, 0x9e, 0x80, 0xf7, 0xe1, 0xe5, 0x90, 0xc7, 0x6b,
	0x6c, 0x93, 0xb4, 0xd7, 0x65, 0x66, 0xbe, 0xf9, 0xfd, 0xcf, 0x9f, 0x85, 0xd4, 0x9d, 0x1a, 0xb4,
	0xeb, 0xc6, 0x68, 0xa7, 0xd9, 0x63, 0x54, 0x95, 0xae, 0xa5, 0xda, 0xf2, 0x1f, 0x10, 0xbf, 0xdf,
	0xeb, 0xea, 0x3b, 0x7b, 0x0d, 0xc9, 0x0e, 0xcb, 0x1a, 0x4d, 0x11, 0x2c, 0xc3, 0x55, 0xfa, 0xe6,
	0xd9, 0x7a, 0x60, 0xd6, 0x04, 0xdc, 0xd1, 0x50, 0x78, 0x88, 0xbd, 0x83, 0xcc, 0x99, 0x52, 0xd9,
	0xb2, 0x72, 0x52, 0x2b, 0x5b, 0x84, 0xcb, 0x68, 0xbe, 0xf4, 0x79, 0x9c, 0x8a, 0x19, 0xca, 0xff,
	0x04, 0x90, 0x4e, 0x24, 0xd9, 0x0d, 0xc4, 0x52, 0xd5, 0xf8, 0x93, 0x3e, 0xbc, 0x10, 0x7d, 0xc1,
	0x38, 0x64, 0x8d, 0xc1, 0xa3, 0xd4, 0xad, 0xbd, 0x2b, 0xed, 0xae, 0x08, 0x97, 0xe1, 0x2a, 0x13,
	0xb3, 0x1e, 0x7b, 0x09, 0x57, 0x4e, 0x1e, 0xd0, 0xba, 0xf2, 0xd0, 0x14, 0x11, 0x6d, 0x8f, 0x0d,
	0x76, 0x0b, 0xd7, 0xd3, 0xef, 0x92, 0xca, 0x82, 0x54, 0xce, 0xfa, 0x9d, 0x07, 0xa5, 0x55, 0x85,
	0x45, 0xdc, 0x7b, 0xa0, 0x82, 0x31, 0x58, 0xec, 0xba, 0xad, 0x84, 0xb6, 0xe8, 0x37, 0xff, 0x1d,
	0x40, 0x3a, 0xb9, 0x8d, 0x3d, 0x81, 0x50, 0xd6, 0x64, 0x3d, 0x13, 0xa1, 0xac, 0xbb, 0x1c, 0xa5,
	0x6a, 0x5a, 0x77, 0x21, 0x92, 0x4f, 0x72, 0xab, 0xb0, 0xfe, 0xd0, 0x4d, 0x85, 0x87, 0xd8, 0x2d,
	0x3c, 0xd2, 0xad, 0x23, 0x3e, 0x22, 0xfe, 0x7a, 0xe4, 0x3f, 0xd2, 0x40, 0x0c, 0x00, 0x7b, 0x0e,
	0x89, 0xc5, 0xca, 0xa0, 0xf3, 0x67, 0xf8, 0x8a, 0x7f, 0x85, 0xa4, 0x47, 0xe7, 0x51, 0xe6, 0x43,
	0x94, 0x37, 0x10, 0x1f, 0xcb, 0x7d, 0x8b, 0x94, 0x61, 0x2e, 0xfa, 0x82, 0xbd, 0x82, 0xbc, 0x69,
	0xbf, 0xed, 0x65, 0x75, 0x8f, 0x27, 0xca, 0x26, 0x22, 0xd1, 0x79, 0x93, 0xdf, 0xc3, 0x53, 0x6f,
	0x03, 0x37, 0x68, 0xb0, 0x4b, 0xe5, 0xff, 0x8b, 0x57, 0x90, 0xf4, 0x0e, 0x49, 0xff, 0xd2, 0x05,
	0x7e, 0xce, 0x7f, 0x05, 0x90, 0x4e, 0x42, 0x60, 0x6f, 0xe1, 0xca, 0x0c, 0xb2, 0xfe, 0xd9, 0xbd,
	0x38, 0x5b, 0x1e, 0x00, 0x31, 0xb2, 0xdd, 0x1f, 0xff, 0xcf, 0xa6, 0x7f, 0x19, 0x63, 0xa3, 0x9b,
	0x5a, 0xb9, 0x55, 0xa5, 0x6b, 0x0d, 0xfa, 0xab, 0xc6, 0x06, 0xdf, 0x40, 0xfe, 0x45, 0xd9, 0x07,
	0x77, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x46, 0xa7, 0xdf, 0x71, 0x03, 0x00, 0x00,
}
